languageCode = 'en-us'
title = 'Karl Johnson'
disablePathToLower = true
[params]
  staticURL = 'https://karl-johnson.b-cdn.net/'
  panoURL = 'https://karl-johnson.b-cdn.net/'
  
	email_url = "mailto://k@rljohnson.net"
	github_url = "https://github.com/karl-johnson"
	instagram_url = "https://www.instagram.com/ka.rljohnson/"
	linkedin_url = "https://www.linkedin.com/in/kadotrljohnson/"
	youtube_url = "https://www.youtube.com/channel/UCKy3BTUfhKNZBpajQm80lBw/"